# Generated by Django 5.1.3 on 2025-02-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='self_comment',
        ),
    ]
